In [33]:
import yfinance as yf

# download dataframe

In [35]:
import pandas as pd
with pd.ExcelWriter('stock_data1.xlsx', engine='xlsxwriter') as writer:
    # Write each dataframe to a different worksheet
    Page_Ind.to_excel(writer, sheet_name='Page_Ind')
    KPR_Mill.to_excel(writer, sheet_name='KPR_Mill')
    Trident.to_excel(writer, sheet_name='Trident')
    Welspun_Living.to_excel(writer, sheet_name='Welspun_Living')
    Swan_Energy.to_excel(writer, sheet_name='Swan_Energy')

print("Data saved to stock_data.xlsx with different worksheets.")
#

Data saved to stock_data.xlsx with different worksheets.

In [34]:
# Page_Industries
Page_Ind = yf.download("PAGEIND.NS", start="2019-01-01", end="2023-12-31")

[*********************100%%**********************]  1 of 1 completed

In [3]:
Page_Ind["Page_Ind_Daily_Returns"] = Page_Ind["Close"].pct_change()
Page_Ind

,Open,High,Low,Close,Adj Close,Volume,Page_Ind_Daily_Returns
Date,,,,,,,
2019-01-01,25200.000000,25200.000000,24602.550781,24847.199219,23833.339844,33677,NaN
2019-01-02,24790.000000,25111.000000,24330.000000,24591.150391,23587.742188,29590,-0.010305
2019-01-03,24500.000000,24700.000000,23529.449219,23614.099609,22650.558594,41968,-0.039732
2019-01-04,23800.000000,24000.000000,22532.599609,22663.000000,21738.269531,72358,-0.040277
2019-01-07,22977.650391,23498.800781,21825.000000,21907.550781,21013.640625,169813,-0.033334
...,...,...,...,...,...,...,...
2023-12-22,37480.000000,37777.000000,37181.851562,37612.250000,37612.250000,20574,0.010288
2023-12-26,37870.000000,37870.000000,37400.000000,37564.750000,37564.750000,13279,-0.001263
2023-12-27,37564.750000,37999.898438,37364.800781,37929.449219,37929.449219,25789,0.009709
2023-12-28,37929.449219,38677.601562,37861.101562,38564.898438,38564.898438,33096,0.016753
2023-12-29,38679.949219,38889.199219,38364.050781,38512.750000,38512.750000,16473,-0.001352

In [4]:
# Calculate price differences
delta = Page_Ind['Close'].diff()

# Set up gains and losses
gains = delta.clip(lower=0)
losses = -1 * delta.clip(upper=0)

# Calculate average gains and losses over a 14-day period (common setting)
avg_gain = gains.ewm(com=14, min_periods=14).mean()
avg_loss = losses.ewm(com=14, min_periods=14).mean()

# Calculate the Relative Strength Index (RSI)
rsi = 100 - (100 / (1 + (avg_gain / avg_loss)))

# Add RSI to the DataFrame
Page_Ind['RSI'] = rsi

In [5]:
Page_Ind.head(20)

,Open,High,Low,Close,Adj Close,Volume,Page_Ind_Daily_Returns,RSI
Date,,,,,,,,
2019-01-01,25200.000000,25200.000000,24602.550781,24847.199219,23833.339844,33677,NaN,NaN
2019-01-02,24790.000000,25111.000000,24330.000000,24591.150391,23587.742188,29590,-0.010305,NaN
2019-01-03,24500.000000,24700.000000,23529.449219,23614.099609,22650.558594,41968,-0.039732,NaN
2019-01-04,23800.000000,24000.000000,22532.599609,22663.000000,21738.269531,72358,-0.040277,NaN
2019-01-07,22977.650391,23498.800781,21825.000000,21907.550781,21013.640625,169813,-0.033334,NaN
2019-01-08,21970.000000,23175.000000,21601.199219,23021.599609,22082.228516,119344,0.050852,NaN
2019-01-09,23061.000000,23388.000000,22762.349609,23262.800781,22313.591797,64706,0.010477,NaN
2019-01-10,23300.000000,23399.000000,22900.000000,23176.349609,22230.669922,34167,-0.003716,NaN
2019-01-11,23176.349609,23449.000000,22734.050781,23356.000000,22402.990234,44616,0.007751,NaN
2019-01-14,23191.000000,23899.000000,22960.449219,23817.750000,22845.890625,46614,0.019770,NaN
2019-01-15,24048.000000,24266.500000,23600.000000,23760.599609,22791.082031,52568,-0.002399,NaN
2019-01-16,23725.500000,24023.900391,23110.000000,23361.199219,22407.974609,60637,-0.016809,NaN
2019-01-17,23440.000000,23559.800781,23120.000000,23265.750000,22316.417969,32601,-0.004086,NaN
2019-01-18,23345.000000,23370.000000,22851.800781,22969.699219,22032.449219,32584,-0.012725,NaN
2019-01-21,22969.000000,23340.050781,22780.599609,22954.199219,22017.583984,28852,-0.000675,35.480594
2019-01-22,22501.000000,23083.900391,22415.000000,22590.550781,21668.771484,141081,-0.015842,31.769440
2019-01-23,22504.500000,22860.000000,22501.500000,22808.849609,21878.164062,37842,0.009663,36.070285
2019-01-24,22790.050781,23325.000000,22729.900391,23172.949219,22227.408203,32985,0.015963,42.542509
2019-01-25,23324.800781,23485.000000,22605.050781,22758.199219,21829.580078,51149,-0.017898,37.864008
2019-01-28,22849.000000,22900.000000,22313.000000,22370.800781,21457.988281,25359,-0.017022,34.109962

In [6]:
## Computing Volatility
import numpy as np
# Compute the logarithmic returns using the Closing price
Page_Ind['Log_Ret'] = np.log(Page_Ind['Close'] / Page_Ind['Close'].shift(1))

# Compute Volatility using the pandas rolling standard deviation function
Page_Ind['Volatility'] = Page_Ind['Log_Ret'].rolling(window=14).std() * np.sqrt(14)
Page_Ind.head(30)

# Plot the NIFTY Price series and the Volatility
# hdfc[['Close', 'Volatility']].plot(kind = "line", subplots=True, color='blue',figsize=(8, 6))

,Open,High,Low,Close,Adj Close,Volume,Page_Ind_Daily_Returns,RSI,Log_Ret,Volatility
Date,,,,,,,,,,
2019-01-01,25200.000000,25200.000000,24602.550781,24847.199219,23833.339844,33677,NaN,NaN,NaN,NaN
2019-01-02,24790.000000,25111.000000,24330.000000,24591.150391,23587.742188,29590,-0.010305,NaN,-0.010358,NaN
2019-01-03,24500.000000,24700.000000,23529.449219,23614.099609,22650.558594,41968,-0.039732,NaN,-0.040543,NaN
2019-01-04,23800.000000,24000.000000,22532.599609,22663.000000,21738.269531,72358,-0.040277,NaN,-0.041110,NaN
2019-01-07,22977.650391,23498.800781,21825.000000,21907.550781,21013.640625,169813,-0.033334,NaN,-0.033902,NaN
2019-01-08,21970.000000,23175.000000,21601.199219,23021.599609,22082.228516,119344,0.050852,NaN,0.049602,NaN
2019-01-09,23061.000000,23388.000000,22762.349609,23262.800781,22313.591797,64706,0.010477,NaN,0.010423,NaN
2019-01-10,23300.000000,23399.000000,22900.000000,23176.349609,22230.669922,34167,-0.003716,NaN,-0.003723,NaN
2019-01-11,23176.349609,23449.000000,22734.050781,23356.000000,22402.990234,44616,0.007751,NaN,0.007722,NaN
2019-01-14,23191.000000,23899.000000,22960.449219,23817.750000,22845.890625,46614,0.019770,NaN,0.019577,NaN
2019-01-15,24048.000000,24266.500000,23600.000000,23760.599609,22791.082031,52568,-0.002399,NaN,-0.002402,NaN
2019-01-16,23725.500000,24023.900391,23110.000000,23361.199219,22407.974609,60637,-0.016809,NaN,-0.016952,NaN
2019-01-17,23440.000000,23559.800781,23120.000000,23265.750000,22316.417969,32601,-0.004086,NaN,-0.004094,NaN
2019-01-18,23345.000000,23370.000000,22851.800781,22969.699219,22032.449219,32584,-0.012725,NaN,-0.012806,NaN
2019-01-21,22969.000000,23340.050781,22780.599609,22954.199219,22017.583984,28852,-0.000675,35.480594,-0.000675,0.090718
2019-01-22,22501.000000,23083.900391,22415.000000,22590.550781,21668.771484,141081,-0.015842,31.769440,-0.015969,0.091203
2019-01-23,22504.500000,22860.000000,22501.500000,22808.849609,21878.164062,37842,0.009663,36.070285,0.009617,0.084314
2019-01-24,22790.050781,23325.000000,22729.900391,23172.949219,22227.408203,32985,0.015963,42.542509,0.015837,0.074922
2019-01-25,23324.800781,23485.000000,22605.050781,22758.199219,21829.580078,51149,-0.017898,37.864008,-0.018060,0.068215
2019-01-28,22849.000000,22900.000000,22313.000000,22370.800781,21457.988281,25359,-0.017022,34.109962,-0.017169,0.048678
2019-01-29,22370.800781,22979.400391,22350.000000,22826.750000,21895.333984,25839,0.020381,41.432348,0.020177,0.052217
2019-01-30,22985.000000,23375.949219,22622.900391,23157.699219,22212.777344,30436,0.014498,46.091415,0.014394,0.054427
2019-01-31,23340.000000,23493.849609,22969.150391,23370.000000,22416.416016,65841,0.009168,48.886104,0.009126,0.054661
2019-02-01,23360.000000,24171.250000,23300.599609,24039.050781,23058.173828,48386,0.028629,56.500428,0.028226,0.058537
2019-02-04,24039.000000,24560.849609,23850.000000,24201.449219,23213.937500,29121,0.006756,58.122820,0.006733,0.058735
2019-02-05,24202.849609,24448.000000,24061.750000,24234.550781,23245.687500,21635,0.001368,58.461161,0.001367,0.055359
2019-02-06,24350.000000,24350.000000,24050.000000,24177.099609,23190.585938,26142,-0.002371,57.595830,-0.002373,0.055161
2019-02-07,24199.000000,24625.000000,23775.050781,23881.599609,22907.142578,26574,-0.012222,53.252003,-0.012298,0.055009
2019-02-08,23710.000000,23985.400391,23500.000000,23570.099609,22608.355469,23385,-0.013044,49.071978,-0.013129,0.057217
2019-02-11,23425.550781,23793.800781,23311.000000,23609.650391,22646.287109,16211,0.001678,49.610058,0.001677,0.053910

In [7]:
# Calculate the 14-day simple moving average of the closing prices
Page_Ind["Moving_Average"] = Page_Ind['Close'].rolling(window=14).mean()

Page_Ind.head(30)

,Open,High,Low,Close,Adj Close,Volume,Page_Ind_Daily_Returns,RSI,Log_Ret,Volatility,Moving_Average
Date,,,,,,,,,,,
2019-01-01,25200.000000,25200.000000,24602.550781,24847.199219,23833.339844,33677,NaN,NaN,NaN,NaN,NaN
2019-01-02,24790.000000,25111.000000,24330.000000,24591.150391,23587.742188,29590,-0.010305,NaN,-0.010358,NaN,NaN
2019-01-03,24500.000000,24700.000000,23529.449219,23614.099609,22650.558594,41968,-0.039732,NaN,-0.040543,NaN,NaN
2019-01-04,23800.000000,24000.000000,22532.599609,22663.000000,21738.269531,72358,-0.040277,NaN,-0.041110,NaN,NaN
2019-01-07,22977.650391,23498.800781,21825.000000,21907.550781,21013.640625,169813,-0.033334,NaN,-0.033902,NaN,NaN
2019-01-08,21970.000000,23175.000000,21601.199219,23021.599609,22082.228516,119344,0.050852,NaN,0.049602,NaN,NaN
2019-01-09,23061.000000,23388.000000,22762.349609,23262.800781,22313.591797,64706,0.010477,NaN,0.010423,NaN,NaN
2019-01-10,23300.000000,23399.000000,22900.000000,23176.349609,22230.669922,34167,-0.003716,NaN,-0.003723,NaN,NaN
2019-01-11,23176.349609,23449.000000,22734.050781,23356.000000,22402.990234,44616,0.007751,NaN,0.007722,NaN,NaN
2019-01-14,23191.000000,23899.000000,22960.449219,23817.750000,22845.890625,46614,0.019770,NaN,0.019577,NaN,NaN
2019-01-15,24048.000000,24266.500000,23600.000000,23760.599609,22791.082031,52568,-0.002399,NaN,-0.002402,NaN,NaN
2019-01-16,23725.500000,24023.900391,23110.000000,23361.199219,22407.974609,60637,-0.016809,NaN,-0.016952,NaN,NaN
2019-01-17,23440.000000,23559.800781,23120.000000,23265.750000,22316.417969,32601,-0.004086,NaN,-0.004094,NaN,NaN
2019-01-18,23345.000000,23370.000000,22851.800781,22969.699219,22032.449219,32584,-0.012725,NaN,-0.012806,NaN,23401.053432
2019-01-21,22969.000000,23340.050781,22780.599609,22954.199219,22017.583984,28852,-0.000675,35.480594,-0.000675,0.090718,23265.839146
2019-01-22,22501.000000,23083.900391,22415.000000,22590.550781,21668.771484,141081,-0.015842,31.769440,-0.015969,0.091203,23122.939174
2019-01-23,22504.500000,22860.000000,22501.500000,22808.849609,21878.164062,37842,0.009663,36.070285,0.009617,0.084314,23065.421317
2019-01-24,22790.050781,23325.000000,22729.900391,23172.949219,22227.408203,32985,0.015963,42.542509,0.015837,0.074922,23101.846261
2019-01-25,23324.800781,23485.000000,22605.050781,22758.199219,21829.580078,51149,-0.017898,37.864008,-0.018060,0.068215,23162.606864
2019-01-28,22849.000000,22900.000000,22313.000000,22370.800781,21457.988281,25359,-0.017022,34.109962,-0.017169,0.048678,23116.121233
2019-01-29,22370.800781,22979.400391,22350.000000,22826.750000,21895.333984,25839,0.020381,41.432348,0.020177,0.052217,23084.974749
2019-01-30,22985.000000,23375.949219,22622.900391,23157.699219,22212.777344,30436,0.014498,46.091415,0.014394,0.054427,23083.642578
2019-01-31,23340.000000,23493.849609,22969.150391,23370.000000,22416.416016,65841,0.009168,48.886104,0.009126,0.054661,23084.642578
2019-02-01,23360.000000,24171.250000,23300.599609,24039.050781,23058.173828,48386,0.028629,56.500428,0.028226,0.058537,23100.449777
2019-02-04,24039.000000,24560.849609,23850.000000,24201.449219,23213.937500,29121,0.006756,58.122820,0.006733,0.058735,23131.939035
2019-02-05,24202.849609,24448.000000,24061.750000,24234.550781,23245.687500,21635,0.001368,58.461161,0.001367,0.055359,23194.321289
2019-02-06,24350.000000,24350.000000,24050.000000,24177.099609,23190.585938,26142,-0.002371,57.595830,-0.002373,0.055161,23259.417690
2019-02-07,24199.000000,24625.000000,23775.050781,23881.599609,22907.142578,26574,-0.012222,53.252003,-0.012298,0.055009,23324.553432
2019-02-08,23710.000000,23985.400391,23500.000000,23570.099609,22608.355469,23385,-0.013044,49.071978,-0.013129,0.057217,23368.546317
2019-02-11,23425.550781,23793.800781,23311.000000,23609.650391,22646.287109,16211,0.001678,49.610058,0.001677,0.053910,23441.339146

In [8]:
#K.P.R Mill Limited
KPR_Mill = yf.download("KPRMILL.NS", start="2019-01-01", end="2023-12-31")

[*********************100%%**********************]  1 of 1 completed

In [9]:
KPR_Mill["KPR_Mill_Daily_Returns"] = KPR_Mill["Close"].pct_change()
KPR_Mill

,Open,High,Low,Close,Adj Close,Volume,KPR_Mill_Daily_Returns
Date,,,,,,,
2019-01-01,112.080002,112.790001,111.470001,112.050003,109.892433,26810,NaN
2019-01-02,112.190002,112.190002,110.709999,111.070000,108.931305,31745,-0.008746
2019-01-03,111.110001,112.949997,111.000000,111.300003,109.156876,59550,0.002071
2019-01-04,111.669998,111.820000,108.800003,109.260002,107.156158,68120,-0.018329
2019-01-07,110.580002,110.580002,107.199997,107.720001,105.645798,74415,-0.014095
...,...,...,...,...,...,...,...
2023-12-22,842.650024,848.900024,817.849976,833.250000,833.250000,203391,-0.005075
2023-12-26,833.250000,838.000000,820.000000,824.150024,824.150024,102444,-0.010921
2023-12-27,823.000000,829.799988,816.250000,820.250000,820.250000,139243,-0.004732
2023-12-28,820.250000,827.349976,815.599976,824.049988,824.049988,239696,0.004633
2023-12-29,826.000000,834.000000,816.000000,824.799988,824.799988,151046,0.000910

In [10]:
# Calculate price differences
delta = KPR_Mill['Close'].diff()

# Set up gains and losses
gains = delta.clip(lower=0)
losses = -1 * delta.clip(upper=0)

# Calculate average gains and losses over a 14-day period (common setting)
avg_gain = gains.ewm(com=14, min_periods=14).mean()
avg_loss = losses.ewm(com=14, min_periods=14).mean()

# Calculate the Relative Strength Index (RSI)
rsi = 100 - (100 / (1 + (avg_gain / avg_loss)))

# Add RSI to the DataFrame
KPR_Mill['RSI'] = rsi

In [11]:
KPR_Mill.head(20)

,Open,High,Low,Close,Adj Close,Volume,KPR_Mill_Daily_Returns,RSI
Date,,,,,,,,
2019-01-01,112.080002,112.790001,111.470001,112.050003,109.892433,26810,NaN,NaN
2019-01-02,112.190002,112.190002,110.709999,111.070000,108.931305,31745,-0.008746,NaN
2019-01-03,111.110001,112.949997,111.000000,111.300003,109.156876,59550,0.002071,NaN
2019-01-04,111.669998,111.820000,108.800003,109.260002,107.156158,68120,-0.018329,NaN
2019-01-07,110.580002,110.580002,107.199997,107.720001,105.645798,74415,-0.014095,NaN
2019-01-08,107.800003,108.959999,106.599998,107.900002,105.822334,129535,0.001671,NaN
2019-01-09,108.169998,108.169998,106.750000,106.889999,104.831787,91935,-0.009361,NaN
2019-01-10,107.019997,107.660004,106.309998,106.620003,104.566994,74480,-0.002526,NaN
2019-01-11,106.349998,107.089996,104.419998,104.580002,102.566269,79900,-0.019133,NaN
2019-01-14,104.800003,104.800003,102.239998,103.029999,101.046104,908835,-0.014821,NaN
2019-01-15,103.209999,108.000000,103.209999,106.040001,103.998154,442290,0.029215,NaN
2019-01-16,107.000000,107.739998,106.000000,106.080002,104.037376,54000,0.000377,NaN
2019-01-17,106.080002,106.779999,106.000000,106.250000,104.204109,38915,0.001603,NaN
2019-01-18,106.669998,107.199997,105.800003,106.099998,104.056992,102825,-0.001412,NaN
2019-01-21,107.599998,107.599998,106.000000,106.070000,104.027580,61180,-0.000283,32.647397
2019-01-22,106.050003,106.800003,105.199997,106.040001,103.998154,60115,-0.000283,32.519207
2019-01-23,106.410004,107.379997,106.000000,106.919998,104.861206,50375,0.008299,39.932151
2019-01-24,106.309998,106.779999,106.000000,106.370003,104.321808,61125,-0.005144,37.195955
2019-01-25,106.620003,107.529999,106.000000,106.000000,103.958916,56500,-0.003478,35.445331
2019-01-28,104.279999,108.389999,103.309998,107.959999,105.881172,211175,0.018491,49.054137

In [12]:
## Computing Volatility
import numpy as np
# Compute the logarithmic returns using the Closing price
KPR_Mill['Log_Ret'] = np.log(KPR_Mill['Close'] / KPR_Mill['Close'].shift(1))

# Compute Volatility using the pandas rolling standard deviation function
KPR_Mill['Volatility'] = KPR_Mill['Log_Ret'].rolling(window=14).std() * np.sqrt(14)
KPR_Mill.head(30)

# Plot the NIFTY Price series and the Volatility
# hdfc[['Close', 'Volatility']].plot(kind = "line", subplots=True, color='blue',figsize=(8, 6))

,Open,High,Low,Close,Adj Close,Volume,KPR_Mill_Daily_Returns,RSI,Log_Ret,Volatility
Date,,,,,,,,,,
2019-01-01,112.080002,112.790001,111.470001,112.050003,109.892433,26810,NaN,NaN,NaN,NaN
2019-01-02,112.190002,112.190002,110.709999,111.070000,108.931305,31745,-0.008746,NaN,-0.008785,NaN
2019-01-03,111.110001,112.949997,111.000000,111.300003,109.156876,59550,0.002071,NaN,0.002069,NaN
2019-01-04,111.669998,111.820000,108.800003,109.260002,107.156158,68120,-0.018329,NaN,-0.018499,NaN
2019-01-07,110.580002,110.580002,107.199997,107.720001,105.645798,74415,-0.014095,NaN,-0.014195,NaN
2019-01-08,107.800003,108.959999,106.599998,107.900002,105.822334,129535,0.001671,NaN,0.001670,NaN
2019-01-09,108.169998,108.169998,106.750000,106.889999,104.831787,91935,-0.009361,NaN,-0.009405,NaN
2019-01-10,107.019997,107.660004,106.309998,106.620003,104.566994,74480,-0.002526,NaN,-0.002529,NaN
2019-01-11,106.349998,107.089996,104.419998,104.580002,102.566269,79900,-0.019133,NaN,-0.019319,NaN
2019-01-14,104.800003,104.800003,102.239998,103.029999,101.046104,908835,-0.014821,NaN,-0.014932,NaN
2019-01-15,103.209999,108.000000,103.209999,106.040001,103.998154,442290,0.029215,NaN,0.028796,NaN
2019-01-16,107.000000,107.739998,106.000000,106.080002,104.037376,54000,0.000377,NaN,0.000377,NaN
2019-01-17,106.080002,106.779999,106.000000,106.250000,104.204109,38915,0.001603,NaN,0.001601,NaN
2019-01-18,106.669998,107.199997,105.800003,106.099998,104.056992,102825,-0.001412,NaN,-0.001413,NaN
2019-01-21,107.599998,107.599998,106.000000,106.070000,104.027580,61180,-0.000283,32.647397,-0.000283,0.045686
2019-01-22,106.050003,106.800003,105.199997,106.040001,103.998154,60115,-0.000283,32.519207,-0.000283,0.045501
2019-01-23,106.410004,107.379997,106.000000,106.919998,104.861206,50375,0.008299,39.932151,0.008264,0.046696
2019-01-24,106.309998,106.779999,106.000000,106.370003,104.321808,61125,-0.005144,37.195955,-0.005157,0.043696
2019-01-25,106.620003,107.529999,106.000000,106.000000,103.958916,56500,-0.003478,35.445331,-0.003485,0.041723
2019-01-28,104.279999,108.389999,103.309998,107.959999,105.881172,211175,0.018491,49.054137,0.018322,0.046035
2019-01-29,108.989998,108.989998,105.400002,106.980003,104.920052,1369105,-0.009077,44.076420,-0.009119,0.045972
2019-01-30,106.260002,108.000000,105.790001,106.089996,104.047180,554340,-0.008319,40.115474,-0.008354,0.046689
2019-01-31,106.300003,106.779999,104.279999,104.830002,102.811447,37890,-0.011877,35.303250,-0.011948,0.043968
2019-02-01,107.970001,107.970001,104.400002,106.250000,104.204109,547910,0.013546,43.488848,0.013455,0.042609
2019-02-04,104.519997,105.550003,102.849998,103.930000,101.928787,102655,-0.021835,35.603453,-0.022077,0.038591
2019-02-05,104.150002,107.360001,103.110001,105.320000,103.292023,78420,0.013374,42.317433,0.013286,0.041307
2019-02-06,105.209999,105.610001,102.809998,103.949997,101.948387,56280,-0.013008,38.120378,-0.013093,0.043073
2019-02-07,103.809998,105.349998,103.209999,103.769997,101.771851,25185,-0.001732,37.595478,-0.001733,0.043073
2019-02-08,102.809998,106.599998,102.809998,105.910004,103.870651,36550,0.020623,46.907740,0.020413,0.048391
2019-02-11,106.040001,106.040001,103.989998,105.330002,103.301826,544040,-0.005476,44.959520,-0.005491,0.048690

In [13]:
# Calculate the 14-day simple moving average of the closing prices
KPR_Mill["Moving_Average"] = KPR_Mill['Close'].rolling(window=14).mean()

KPR_Mill.head(30)

,Open,High,Low,Close,Adj Close,Volume,KPR_Mill_Daily_Returns,RSI,Log_Ret,Volatility,Moving_Average
Date,,,,,,,,,,,
2019-01-01,112.080002,112.790001,111.470001,112.050003,109.892433,26810,NaN,NaN,NaN,NaN,NaN
2019-01-02,112.190002,112.190002,110.709999,111.070000,108.931305,31745,-0.008746,NaN,-0.008785,NaN,NaN
2019-01-03,111.110001,112.949997,111.000000,111.300003,109.156876,59550,0.002071,NaN,0.002069,NaN,NaN
2019-01-04,111.669998,111.820000,108.800003,109.260002,107.156158,68120,-0.018329,NaN,-0.018499,NaN,NaN
2019-01-07,110.580002,110.580002,107.199997,107.720001,105.645798,74415,-0.014095,NaN,-0.014195,NaN,NaN
2019-01-08,107.800003,108.959999,106.599998,107.900002,105.822334,129535,0.001671,NaN,0.001670,NaN,NaN
2019-01-09,108.169998,108.169998,106.750000,106.889999,104.831787,91935,-0.009361,NaN,-0.009405,NaN,NaN
2019-01-10,107.019997,107.660004,106.309998,106.620003,104.566994,74480,-0.002526,NaN,-0.002529,NaN,NaN
2019-01-11,106.349998,107.089996,104.419998,104.580002,102.566269,79900,-0.019133,NaN,-0.019319,NaN,NaN
2019-01-14,104.800003,104.800003,102.239998,103.029999,101.046104,908835,-0.014821,NaN,-0.014932,NaN,NaN
2019-01-15,103.209999,108.000000,103.209999,106.040001,103.998154,442290,0.029215,NaN,0.028796,NaN,NaN
2019-01-16,107.000000,107.739998,106.000000,106.080002,104.037376,54000,0.000377,NaN,0.000377,NaN,NaN
2019-01-17,106.080002,106.779999,106.000000,106.250000,104.204109,38915,0.001603,NaN,0.001601,NaN,NaN
2019-01-18,106.669998,107.199997,105.800003,106.099998,104.056992,102825,-0.001412,NaN,-0.001413,NaN,107.492144
2019-01-21,107.599998,107.599998,106.000000,106.070000,104.027580,61180,-0.000283,32.647397,-0.000283,0.045686,107.065001
2019-01-22,106.050003,106.800003,105.199997,106.040001,103.998154,60115,-0.000283,32.519207,-0.000283,0.045501,106.705715
2019-01-23,106.410004,107.379997,106.000000,106.919998,104.861206,50375,0.008299,39.932151,0.008264,0.046696,106.392858
2019-01-24,106.309998,106.779999,106.000000,106.370003,104.321808,61125,-0.005144,37.195955,-0.005157,0.043696,106.186429
2019-01-25,106.620003,107.529999,106.000000,106.000000,103.958916,56500,-0.003478,35.445331,-0.003485,0.041723,106.063572
2019-01-28,104.279999,108.389999,103.309998,107.959999,105.881172,211175,0.018491,49.054137,0.018322,0.046035,106.067857
2019-01-29,108.989998,108.989998,105.400002,106.980003,104.920052,1369105,-0.009077,44.076420,-0.009119,0.045972,106.074286
2019-01-30,106.260002,108.000000,105.790001,106.089996,104.047180,554340,-0.008319,40.115474,-0.008354,0.046689,106.036429
2019-01-31,106.300003,106.779999,104.279999,104.830002,102.811447,37890,-0.011877,35.303250,-0.011948,0.043968,106.054286
2019-02-01,107.970001,107.970001,104.400002,106.250000,104.204109,547910,0.013546,43.488848,0.013455,0.042609,106.284286
2019-02-04,104.519997,105.550003,102.849998,103.930000,101.928787,102655,-0.021835,35.603453,-0.022077,0.038591,106.133572
2019-02-05,104.150002,107.360001,103.110001,105.320000,103.292023,78420,0.013374,42.317433,0.013286,0.041307,106.079286
2019-02-06,105.209999,105.610001,102.809998,103.949997,101.948387,56280,-0.013008,38.120378,-0.013093,0.043073,105.915000
2019-02-07,103.809998,105.349998,103.209999,103.769997,101.771851,25185,-0.001732,37.595478,-0.001733,0.043073,105.748571
2019-02-08,102.809998,106.599998,102.809998,105.910004,103.870651,36550,0.020623,46.907740,0.020413,0.048391,105.737143
2019-02-11,106.040001,106.040001,103.989998,105.330002,103.301826,544040,-0.005476,44.959520,-0.005491,0.048690,105.686429

In [14]:
# Trident
Trident = yf.download("TRIDENT.NS", start="2019-01-01", end="2023-12-31")

[*********************100%%**********************]  1 of 1 completed

In [15]:
Trident["Trident_Daily_Returns"] = Trident["Close"].pct_change()
Trident

,Open,High,Low,Close,Adj Close,Volume,Trident_Daily_Returns
Date,,,,,,,
2019-01-01,6.620000,6.895000,6.620000,6.820000,5.939979,13560030,NaN
2019-01-02,6.770000,6.840000,6.650000,6.745000,5.874656,4528870,-0.010997
2019-01-03,6.790000,6.850000,6.710000,6.730000,5.861592,5166720,-0.002224
2019-01-04,6.765000,6.790000,6.630000,6.675000,5.813689,3540830,-0.008172
2019-01-07,6.700000,6.800000,6.700000,6.725000,5.857237,3584990,0.007491
...,...,...,...,...,...,...,...
2023-12-22,36.500000,36.650002,35.900002,36.150002,36.150002,7525883,0.002774
2023-12-26,36.400002,36.450001,35.900002,36.049999,36.049999,7552200,-0.002766
2023-12-27,36.400002,36.400002,35.849998,36.099998,36.099998,7051280,0.001387
2023-12-28,36.099998,36.200001,35.849998,35.900002,35.900002,5274318,-0.005540
2023-12-29,35.950001,36.450001,35.700001,36.299999,36.299999,8058888,0.011142

In [16]:
# Calculate price differences
delta = Trident['Close'].diff()

# Set up gains and losses
gains = delta.clip(lower=0)
losses = -1 * delta.clip(upper=0)

# Calculate average gains and losses over a 14-day period (common setting)
avg_gain = gains.ewm(com=14, min_periods=14).mean()
avg_loss = losses.ewm(com=14, min_periods=14).mean()

# Calculate the Relative Strength Index (RSI)
rsi = 100 - (100 / (1 + (avg_gain / avg_loss)))

# Add RSI to the DataFrame
Trident['RSI'] = rsi

In [17]:
Trident.head(20)

,Open,High,Low,Close,Adj Close,Volume,Trident_Daily_Returns,RSI
Date,,,,,,,,
2019-01-01,6.620,6.895,6.620,6.820,5.939979,13560030,NaN,NaN
2019-01-02,6.770,6.840,6.650,6.745,5.874656,4528870,-0.010997,NaN
2019-01-03,6.790,6.850,6.710,6.730,5.861592,5166720,-0.002224,NaN
2019-01-04,6.765,6.790,6.630,6.675,5.813689,3540830,-0.008172,NaN
2019-01-07,6.700,6.800,6.700,6.725,5.857237,3584990,0.007491,NaN
2019-01-08,6.750,6.880,6.725,6.790,5.913850,5611110,0.009665,NaN
2019-01-09,6.825,6.860,6.735,6.770,5.896431,2903480,-0.002946,NaN
2019-01-10,6.875,7.170,6.850,7.095,6.179494,32175270,0.048006,NaN
2019-01-11,7.095,7.190,7.060,7.095,6.179494,11060100,0.000000,NaN
2019-01-14,7.095,7.130,6.955,6.990,6.088043,6074530,-0.014799,NaN
2019-01-15,7.025,7.570,7.020,7.275,6.336268,80213560,0.040773,NaN
2019-01-16,7.285,7.350,7.040,7.070,6.157720,17148720,-0.028179,NaN
2019-01-17,7.100,7.190,7.030,7.080,6.166429,9352690,0.001414,NaN
2019-01-18,7.150,7.150,6.960,6.995,6.092398,5176140,-0.012006,NaN
2019-01-21,7.035,7.040,6.800,6.810,5.931269,5816760,-0.026447,45.575175
2019-01-22,6.900,7.200,6.860,7.005,6.101108,19603660,0.028634,54.499043
2019-01-23,7.000,7.000,6.835,6.895,6.005301,4684080,-0.015703,49.585114
2019-01-24,6.820,6.840,6.625,6.640,5.885639,5233380,-0.036983,40.512381
2019-01-25,6.680,6.725,6.510,6.565,5.819159,6552210,-0.011295,38.303807
2019-01-28,6.505,6.525,6.400,6.455,5.721656,5343850,-0.016756,35.281316

In [18]:
## Computing Volatility
import numpy as np
# Compute the logarithmic returns using the Closing price
Trident['Log_Ret'] = np.log(Trident['Close'] / Trident['Close'].shift(1))

# Compute Volatility using the pandas rolling standard deviation function
Trident['Volatility'] = Trident['Log_Ret'].rolling(window=14).std() * np.sqrt(14)
Trident.head(30)

# Plot the NIFTY Price series and the Volatility
# hdfc[['Close', 'Volatility']].plot(kind = "line", subplots=True, color='blue',figsize=(8, 6))

,Open,High,Low,Close,Adj Close,Volume,Trident_Daily_Returns,RSI,Log_Ret,Volatility
Date,,,,,,,,,,
2019-01-01,6.620,6.895,6.620,6.820,5.939979,13560030,NaN,NaN,NaN,NaN
2019-01-02,6.770,6.840,6.650,6.745,5.874656,4528870,-0.010997,NaN,-0.011058,NaN
2019-01-03,6.790,6.850,6.710,6.730,5.861592,5166720,-0.002224,NaN,-0.002226,NaN
2019-01-04,6.765,6.790,6.630,6.675,5.813689,3540830,-0.008172,NaN,-0.008206,NaN
2019-01-07,6.700,6.800,6.700,6.725,5.857237,3584990,0.007491,NaN,0.007463,NaN
2019-01-08,6.750,6.880,6.725,6.790,5.913850,5611110,0.009665,NaN,0.009619,NaN
2019-01-09,6.825,6.860,6.735,6.770,5.896431,2903480,-0.002946,NaN,-0.002950,NaN
2019-01-10,6.875,7.170,6.850,7.095,6.179494,32175270,0.048006,NaN,0.046889,NaN
2019-01-11,7.095,7.190,7.060,7.095,6.179494,11060100,0.000000,NaN,0.000000,NaN
2019-01-14,7.095,7.130,6.955,6.990,6.088043,6074530,-0.014799,NaN,-0.014910,NaN
2019-01-15,7.025,7.570,7.020,7.275,6.336268,80213560,0.040773,NaN,0.039963,NaN
2019-01-16,7.285,7.350,7.040,7.070,6.157720,17148720,-0.028179,NaN,-0.028583,NaN
2019-01-17,7.100,7.190,7.030,7.080,6.166429,9352690,0.001414,NaN,0.001413,NaN
2019-01-18,7.150,7.150,6.960,6.995,6.092398,5176140,-0.012006,NaN,-0.012078,NaN
2019-01-21,7.035,7.040,6.800,6.810,5.931269,5816760,-0.026447,45.575175,-0.026803,0.080735
2019-01-22,6.900,7.200,6.860,7.005,6.101108,19603660,0.028634,54.499043,0.028232,0.084469
2019-01-23,7.000,7.000,6.835,6.895,6.005301,4684080,-0.015703,49.585114,-0.015828,0.086397
2019-01-24,6.820,6.840,6.625,6.640,5.885639,5233380,-0.036983,40.512381,-0.037685,0.094680
2019-01-25,6.680,6.725,6.510,6.565,5.819159,6552210,-0.011295,38.303807,-0.011359,0.094872
2019-01-28,6.505,6.525,6.400,6.455,5.721656,5343850,-0.016756,35.281316,-0.016898,0.095164
2019-01-29,6.450,6.640,6.355,6.555,5.810295,4283750,0.015492,39.900483,0.015373,0.097047
2019-01-30,6.565,6.680,6.540,6.660,5.903366,4459800,0.016018,44.367482,0.015891,0.084230
2019-01-31,6.675,6.750,6.630,6.675,5.916662,2761270,0.002252,44.993282,0.002250,0.084389
2019-02-01,6.720,6.745,6.525,6.550,5.805864,3237530,-0.018727,40.886868,-0.018904,0.085019
2019-02-04,6.565,6.565,6.450,6.485,5.748249,2041460,-0.009924,38.908415,-0.009973,0.070173
2019-02-05,6.510,6.510,6.130,6.215,5.508923,4362300,-0.041635,32.014034,-0.042526,0.075699
2019-02-06,6.230,6.260,5.970,6.095,5.402555,5754550,-0.019308,29.522922,-0.019497,0.075428
2019-02-07,6.105,6.315,6.050,6.290,5.575401,3774330,0.031993,37.931792,0.031492,0.086362
2019-02-08,6.330,6.400,6.165,6.240,5.531082,4907210,-0.007949,36.727905,-0.007981,0.083867
2019-02-11,6.220,6.235,6.060,6.130,5.433579,4463860,-0.017628,34.171502,-0.017785,0.075725

In [19]:
# Calculate the 14-day simple moving average of the closing prices
Trident["Moving_Average"] = Trident['Close'].rolling(window=14).mean()

Trident.head(30)

,Open,High,Low,Close,Adj Close,Volume,Trident_Daily_Returns,RSI,Log_Ret,Volatility,Moving_Average
Date,,,,,,,,,,,
2019-01-01,6.620,6.895,6.620,6.820,5.939979,13560030,NaN,NaN,NaN,NaN,NaN
2019-01-02,6.770,6.840,6.650,6.745,5.874656,4528870,-0.010997,NaN,-0.011058,NaN,NaN
2019-01-03,6.790,6.850,6.710,6.730,5.861592,5166720,-0.002224,NaN,-0.002226,NaN,NaN
2019-01-04,6.765,6.790,6.630,6.675,5.813689,3540830,-0.008172,NaN,-0.008206,NaN,NaN
2019-01-07,6.700,6.800,6.700,6.725,5.857237,3584990,0.007491,NaN,0.007463,NaN,NaN
2019-01-08,6.750,6.880,6.725,6.790,5.913850,5611110,0.009665,NaN,0.009619,NaN,NaN
2019-01-09,6.825,6.860,6.735,6.770,5.896431,2903480,-0.002946,NaN,-0.002950,NaN,NaN
2019-01-10,6.875,7.170,6.850,7.095,6.179494,32175270,0.048006,NaN,0.046889,NaN,NaN
2019-01-11,7.095,7.190,7.060,7.095,6.179494,11060100,0.000000,NaN,0.000000,NaN,NaN
2019-01-14,7.095,7.130,6.955,6.990,6.088043,6074530,-0.014799,NaN,-0.014910,NaN,NaN
2019-01-15,7.025,7.570,7.020,7.275,6.336268,80213560,0.040773,NaN,0.039963,NaN,NaN
2019-01-16,7.285,7.350,7.040,7.070,6.157720,17148720,-0.028179,NaN,-0.028583,NaN,NaN
2019-01-17,7.100,7.190,7.030,7.080,6.166429,9352690,0.001414,NaN,0.001413,NaN,NaN
2019-01-18,7.150,7.150,6.960,6.995,6.092398,5176140,-0.012006,NaN,-0.012078,NaN,6.918214
2019-01-21,7.035,7.040,6.800,6.810,5.931269,5816760,-0.026447,45.575175,-0.026803,0.080735,6.917500
2019-01-22,6.900,7.200,6.860,7.005,6.101108,19603660,0.028634,54.499043,0.028232,0.084469,6.936071
2019-01-23,7.000,7.000,6.835,6.895,6.005301,4684080,-0.015703,49.585114,-0.015828,0.086397,6.947857
2019-01-24,6.820,6.840,6.625,6.640,5.885639,5233380,-0.036983,40.512381,-0.037685,0.094680,6.945357
2019-01-25,6.680,6.725,6.510,6.565,5.819159,6552210,-0.011295,38.303807,-0.011359,0.094872,6.933929
2019-01-28,6.505,6.525,6.400,6.455,5.721656,5343850,-0.016756,35.281316,-0.016898,0.095164,6.910000
2019-01-29,6.450,6.640,6.355,6.555,5.810295,4283750,0.015492,39.900483,0.015373,0.097047,6.894643
2019-01-30,6.565,6.680,6.540,6.660,5.903366,4459800,0.016018,44.367482,0.015891,0.084230,6.863571
2019-01-31,6.675,6.750,6.630,6.675,5.916662,2761270,0.002252,44.993282,0.002250,0.084389,6.833571
2019-02-01,6.720,6.745,6.525,6.550,5.805864,3237530,-0.018727,40.886868,-0.018904,0.085019,6.802143
2019-02-04,6.565,6.565,6.450,6.485,5.748249,2041460,-0.009924,38.908415,-0.009973,0.070173,6.745714
2019-02-05,6.510,6.510,6.130,6.215,5.508923,4362300,-0.041635,32.014034,-0.042526,0.075699,6.684643
2019-02-06,6.230,6.260,5.970,6.095,5.402555,5754550,-0.019308,29.522922,-0.019497,0.075428,6.614286
2019-02-07,6.105,6.315,6.050,6.290,5.575401,3774330,0.031993,37.931792,0.031492,0.086362,6.563929
2019-02-08,6.330,6.400,6.165,6.240,5.531082,4907210,-0.007949,36.727905,-0.007981,0.083867,6.523214
2019-02-11,6.220,6.235,6.060,6.130,5.433579,4463860,-0.017628,34.171502,-0.017785,0.075725,6.460714

In [20]:
# Welspun Living
Welspun_Living = yf.download("WELSPUNLIV.NS", start="2019-01-01", end="2023-12-31")

[*********************100%%**********************]  1 of 1 completed

In [21]:
Welspun_Living["Welspun_Living_Daily_Returns"] = Welspun_Living["Close"].pct_change()
Welspun_Living

,Open,High,Low,Close,Adj Close,Volume,Welspun_Living_Daily_Returns
Date,,,,,,,
2019-01-01,59.799999,60.750000,59.299999,60.500000,57.771790,377138,NaN
2019-01-02,60.450001,62.400002,59.750000,61.349998,58.583466,782890,0.014050
2019-01-03,61.700001,62.250000,60.799999,61.200001,58.440231,398033,-0.002445
2019-01-04,61.200001,61.599998,60.250000,60.849998,58.106010,369574,-0.005719
2019-01-07,61.049999,61.799999,61.000000,61.299999,58.535717,252967,0.007395
...,...,...,...,...,...,...,...
2023-12-22,146.449997,147.800003,142.500000,145.300003,145.300003,3166326,0.004494
2023-12-26,145.300003,146.949997,144.000000,144.250000,144.250000,1068644,-0.007226
2023-12-27,144.000000,146.750000,142.199997,143.449997,143.449997,1411250,-0.005546
2023-12-28,144.000000,146.600006,140.949997,142.050003,142.050003,1391825,-0.009759
2023-12-29,143.449997,145.399994,140.050003,144.449997,144.449997,1856330,0.016895

In [22]:
# Calculate price differences
delta = Welspun_Living['Close'].diff()

# Set up gains and losses
gains = delta.clip(lower=0)
losses = -1 * delta.clip(upper=0)

# Calculate average gains and losses over a 14-day period (common setting)
avg_gain = gains.ewm(com=14, min_periods=14).mean()
avg_loss = losses.ewm(com=14, min_periods=14).mean()

# Calculate the Relative Strength Index (RSI)
rsi = 100 - (100 / (1 + (avg_gain / avg_loss)))

# Add RSI to the DataFrame
Welspun_Living['RSI'] = rsi

In [23]:
Welspun_Living.head(20)

,Open,High,Low,Close,Adj Close,Volume,Welspun_Living_Daily_Returns,RSI
Date,,,,,,,,
2019-01-01,59.799999,60.750000,59.299999,60.500000,57.771790,377138,NaN,NaN
2019-01-02,60.450001,62.400002,59.750000,61.349998,58.583466,782890,0.014050,NaN
2019-01-03,61.700001,62.250000,60.799999,61.200001,58.440231,398033,-0.002445,NaN
2019-01-04,61.200001,61.599998,60.250000,60.849998,58.106010,369574,-0.005719,NaN
2019-01-07,61.049999,61.799999,61.000000,61.299999,58.535717,252967,0.007395,NaN
2019-01-08,61.200001,61.900002,60.750000,61.250000,58.487976,321598,-0.000816,NaN
2019-01-09,61.099998,61.799999,60.549999,61.250000,58.487976,422659,0.000000,NaN
2019-01-10,61.099998,61.900002,61.000000,61.549999,58.774448,255807,0.004898,NaN
2019-01-11,61.700001,65.000000,61.250000,62.150002,59.347389,1062571,0.009748,NaN
2019-01-14,62.200001,62.500000,61.200001,61.500000,58.726696,290487,-0.010459,NaN
2019-01-15,62.150002,63.049999,61.400002,62.599998,59.777096,419450,0.017886,NaN
2019-01-16,62.599998,62.849998,61.299999,61.500000,58.726696,292231,-0.017572,NaN
2019-01-17,61.849998,61.900002,60.700001,61.049999,58.296993,448510,-0.007317,NaN
2019-01-18,61.099998,61.500000,60.150002,60.400002,57.676304,349885,-0.010647,NaN
2019-01-21,60.099998,60.450001,59.650002,60.099998,57.389835,576128,-0.004967,40.600689
2019-01-22,60.200001,60.650002,57.349998,58.950001,56.291691,905600,-0.019135,32.440664
2019-01-23,59.299999,60.200001,58.700001,59.349998,56.673645,398605,0.006785,37.148259
2019-01-24,59.349998,59.750000,58.700001,59.150002,56.482670,603585,-0.003370,35.811464
2019-01-25,59.200001,59.549999,56.750000,57.299999,54.716099,582461,-0.031276,26.397039
2019-01-28,56.200001,58.799999,54.400002,58.599998,55.957474,1164632,0.022688,38.558075

In [24]:
## Computing Volatility
import numpy as np
# Compute the logarithmic returns using the Closing price
Welspun_Living['Log_Ret'] = np.log(Welspun_Living['Close'] / Trident['Close'].shift(1))

# Compute Volatility using the pandas rolling standard deviation function
Welspun_Living['Volatility'] = Welspun_Living['Log_Ret'].rolling(window=14).std() * np.sqrt(14)
Welspun_Living.head(30)

# Plot the NIFTY Price series and the Volatility
# hdfc[['Close', 'Volatility']].plot(kind = "line", subplots=True, color='blue',figsize=(8, 6))

,Open,High,Low,Close,Adj Close,Volume,Welspun_Living_Daily_Returns,RSI,Log_Ret,Volatility
Date,,,,,,,,,,
2019-01-01,59.799999,60.750000,59.299999,60.500000,57.771790,377138,NaN,NaN,NaN,NaN
2019-01-02,60.450001,62.400002,59.750000,61.349998,58.583466,782890,0.014050,NaN,2.196736,NaN
2019-01-03,61.700001,62.250000,60.799999,61.200001,58.440231,398033,-0.002445,NaN,2.205346,NaN
2019-01-04,61.200001,61.599998,60.250000,60.849998,58.106010,369574,-0.005719,NaN,2.201837,NaN
2019-01-07,61.049999,61.799999,61.000000,61.299999,58.535717,252967,0.007395,NaN,2.217411,NaN
2019-01-08,61.200001,61.900002,60.750000,61.250000,58.487976,321598,-0.000816,NaN,2.209132,NaN
2019-01-09,61.099998,61.799999,60.549999,61.250000,58.487976,422659,0.000000,NaN,2.199513,NaN
2019-01-10,61.099998,61.900002,61.000000,61.549999,58.774448,255807,0.004898,NaN,2.207349,NaN
2019-01-11,61.700001,65.000000,61.250000,62.150002,59.347389,1062571,0.009748,NaN,2.170161,NaN
2019-01-14,62.200001,62.500000,61.200001,61.500000,58.726696,290487,-0.010459,NaN,2.159647,NaN
2019-01-15,62.150002,63.049999,61.400002,62.599998,59.777096,419450,0.017886,NaN,2.192285,NaN
2019-01-16,62.599998,62.849998,61.299999,61.500000,58.726696,292231,-0.017572,NaN,2.134593,NaN
2019-01-17,61.849998,61.900002,60.700001,61.049999,58.296993,448510,-0.007317,NaN,2.155833,NaN
2019-01-18,61.099998,61.500000,60.150002,60.400002,57.676304,349885,-0.010647,NaN,2.143715,NaN
2019-01-21,60.099998,60.450001,59.650002,60.099998,57.389835,576128,-0.004967,40.600689,2.150814,0.104859
2019-01-22,60.200001,60.650002,57.349998,58.950001,56.291691,905600,-0.019135,32.440664,2.158298,0.105979
2019-01-23,59.299999,60.200001,58.700001,59.349998,56.673645,398605,0.006785,37.148259,2.136828,0.109715
2019-01-24,59.349998,59.750000,58.700001,59.150002,56.482670,603585,-0.003370,35.811464,2.149280,0.107981
2019-01-25,59.200001,59.549999,56.750000,57.299999,54.716099,582461,-0.031276,26.397039,2.155189,0.096043
2019-01-28,56.200001,58.799999,54.400002,58.599998,55.957474,1164632,0.022688,38.558075,2.188982,0.088058
2019-01-29,59.000000,59.250000,56.099998,58.900002,56.243950,1064592,0.005120,40.969627,2.210986,0.093552
2019-01-30,59.200001,60.200001,58.799999,59.799999,57.103363,521031,0.015280,47.582458,2.210778,0.095259
2019-01-31,60.000000,60.450001,58.799999,60.200001,57.485329,413321,0.006689,50.237072,2.201553,0.101848
2019-02-01,60.000000,60.099998,58.400002,59.400002,56.721401,242211,-0.013289,45.318987,2.185925,0.102975
2019-02-04,59.200001,60.799999,57.500000,58.349998,55.718742,896166,-0.017677,39.834953,2.186994,0.101852
2019-02-05,56.000000,58.500000,55.099998,55.450001,52.949520,540717,-0.049700,29.331634,2.145990,0.098247
2019-02-06,56.000000,56.000000,52.900002,54.250000,51.803635,506205,-0.021641,26.261680,2.166637,0.097148
2019-02-07,54.250000,54.700001,53.000000,53.349998,50.944214,364175,-0.016590,24.224301,2.169405,0.092714
2019-02-08,53.099998,53.299999,52.200001,52.400002,50.037060,1276791,-0.017807,22.270330,2.119946,0.104896
2019-02-11,52.000000,52.349998,50.400002,51.650002,49.320885,2763331,-0.014313,20.847898,2.113510,0.119100

In [25]:
# Calculate the 14-day simple moving average of the closing prices
Welspun_Living["Moving_Average"] = Welspun_Living['Close'].rolling(window=14).mean()

Welspun_Living.head(30)

,Open,High,Low,Close,Adj Close,Volume,Welspun_Living_Daily_Returns,RSI,Log_Ret,Volatility,Moving_Average
Date,,,,,,,,,,,
2019-01-01,59.799999,60.750000,59.299999,60.500000,57.771790,377138,NaN,NaN,NaN,NaN,NaN
2019-01-02,60.450001,62.400002,59.750000,61.349998,58.583466,782890,0.014050,NaN,2.196736,NaN,NaN
2019-01-03,61.700001,62.250000,60.799999,61.200001,58.440231,398033,-0.002445,NaN,2.205346,NaN,NaN
2019-01-04,61.200001,61.599998,60.250000,60.849998,58.106010,369574,-0.005719,NaN,2.201837,NaN,NaN
2019-01-07,61.049999,61.799999,61.000000,61.299999,58.535717,252967,0.007395,NaN,2.217411,NaN,NaN
2019-01-08,61.200001,61.900002,60.750000,61.250000,58.487976,321598,-0.000816,NaN,2.209132,NaN,NaN
2019-01-09,61.099998,61.799999,60.549999,61.250000,58.487976,422659,0.000000,NaN,2.199513,NaN,NaN
2019-01-10,61.099998,61.900002,61.000000,61.549999,58.774448,255807,0.004898,NaN,2.207349,NaN,NaN
2019-01-11,61.700001,65.000000,61.250000,62.150002,59.347389,1062571,0.009748,NaN,2.170161,NaN,NaN
2019-01-14,62.200001,62.500000,61.200001,61.500000,58.726696,290487,-0.010459,NaN,2.159647,NaN,NaN
2019-01-15,62.150002,63.049999,61.400002,62.599998,59.777096,419450,0.017886,NaN,2.192285,NaN,NaN
2019-01-16,62.599998,62.849998,61.299999,61.500000,58.726696,292231,-0.017572,NaN,2.134593,NaN,NaN
2019-01-17,61.849998,61.900002,60.700001,61.049999,58.296993,448510,-0.007317,NaN,2.155833,NaN,NaN
2019-01-18,61.099998,61.500000,60.150002,60.400002,57.676304,349885,-0.010647,NaN,2.143715,NaN,61.317857
2019-01-21,60.099998,60.450001,59.650002,60.099998,57.389835,576128,-0.004967,40.600689,2.150814,0.104859,61.289285
2019-01-22,60.200001,60.650002,57.349998,58.950001,56.291691,905600,-0.019135,32.440664,2.158298,0.105979,61.117857
2019-01-23,59.299999,60.200001,58.700001,59.349998,56.673645,398605,0.006785,37.148259,2.136828,0.109715,60.985714
2019-01-24,59.349998,59.750000,58.700001,59.150002,56.482670,603585,-0.003370,35.811464,2.149280,0.107981,60.864286
2019-01-25,59.200001,59.549999,56.750000,57.299999,54.716099,582461,-0.031276,26.397039,2.155189,0.096043,60.578571
2019-01-28,56.200001,58.799999,54.400002,58.599998,55.957474,1164632,0.022688,38.558075,2.188982,0.088058,60.389285
2019-01-29,59.000000,59.250000,56.099998,58.900002,56.243950,1064592,0.005120,40.969627,2.210986,0.093552,60.221428
2019-01-30,59.200001,60.200001,58.799999,59.799999,57.103363,521031,0.015280,47.582458,2.210778,0.095259,60.096428
2019-01-31,60.000000,60.450001,58.799999,60.200001,57.485329,413321,0.006689,50.237072,2.201553,0.101848,59.957143
2019-02-01,60.000000,60.099998,58.400002,59.400002,56.721401,242211,-0.013289,45.318987,2.185925,0.102975,59.807143
2019-02-04,59.200001,60.799999,57.500000,58.349998,55.718742,896166,-0.017677,39.834953,2.186994,0.101852,59.503571
2019-02-05,56.000000,58.500000,55.099998,55.450001,52.949520,540717,-0.049700,29.331634,2.145990,0.098247,59.071429
2019-02-06,56.000000,56.000000,52.900002,54.250000,51.803635,506205,-0.021641,26.261680,2.166637,0.097148,58.585714
2019-02-07,54.250000,54.700001,53.000000,53.349998,50.944214,364175,-0.016590,24.224301,2.169405,0.092714,58.082143
2019-02-08,53.099998,53.299999,52.200001,52.400002,50.037060,1276791,-0.017807,22.270330,2.119946,0.104896,57.532143
2019-02-11,52.000000,52.349998,50.400002,51.650002,49.320885,2763331,-0.014313,20.847898,2.113510,0.119100,57.010714

In [26]:
# Swan Energy
Swan_Energy = yf.download("SWANENERGY.NS", start="2019-01-01", end="2023-12-31")

[*********************100%%**********************]  1 of 1 completed

In [27]:
Swan_Energy["Swan_Energy_Daily_Returns"] = Swan_Energy["Close"].pct_change()
Swan_Energy

,Open,High,Low,Close,Adj Close,Volume,Swan_Energy_Daily_Returns
Date,,,,,,,
2019-01-01,101.699997,102.300003,99.500000,100.099998,99.774803,267114,NaN
2019-01-02,100.199997,100.900002,97.000000,97.699997,97.382591,326180,-0.023976
2019-01-03,98.250000,99.500000,97.849998,98.800003,98.479034,215418,0.011259
2019-01-04,98.800003,101.000000,98.000000,99.449997,99.126907,219293,0.006579
2019-01-07,100.699997,100.699997,98.050003,98.900002,98.578697,324370,-0.005530
...,...,...,...,...,...,...,...
2023-12-22,502.000000,512.900024,494.000000,506.399994,506.399994,6871825,0.025932
2023-12-26,511.500000,518.200012,498.600006,503.350006,503.350006,3651075,-0.006023
2023-12-27,504.399994,514.000000,498.600006,508.750000,508.750000,18439691,0.010728
2023-12-28,507.000000,515.799988,500.700012,512.849976,512.849976,6211831,0.008059
2023-12-29,520.000000,525.299988,505.149994,511.000000,511.000000,8136438,-0.003607

In [28]:
# Calculate price differences
delta = Swan_Energy['Close'].diff()

# Set up gains and losses
gains = delta.clip(lower=0)
losses = -1 * delta.clip(upper=0)

# Calculate average gains and losses over a 14-day period (common setting)
avg_gain = gains.ewm(com=14, min_periods=14).mean()
avg_loss = losses.ewm(com=14, min_periods=14).mean()

# Calculate the Relative Strength Index (RSI)
rsi = 100 - (100 / (1 + (avg_gain / avg_loss)))

# Add RSI to the DataFrame
Swan_Energy['RSI'] = rsi

In [29]:
Swan_Energy.head(20)

,Open,High,Low,Close,Adj Close,Volume,Swan_Energy_Daily_Returns,RSI
Date,,,,,,,,
2019-01-01,101.699997,102.300003,99.500000,100.099998,99.774803,267114,NaN,NaN
2019-01-02,100.199997,100.900002,97.000000,97.699997,97.382591,326180,-0.023976,NaN
2019-01-03,98.250000,99.500000,97.849998,98.800003,98.479034,215418,0.011259,NaN
2019-01-04,98.800003,101.000000,98.000000,99.449997,99.126907,219293,0.006579,NaN
2019-01-07,100.699997,100.699997,98.050003,98.900002,98.578697,324370,-0.005530,NaN
2019-01-08,99.699997,99.699997,98.099998,98.349998,98.030487,192394,-0.005561,NaN
2019-01-09,99.000000,99.000000,98.000000,98.300003,97.980652,429586,-0.000508,NaN
2019-01-10,99.300003,101.800003,97.400002,99.599998,99.276428,227875,0.013225,NaN
2019-01-11,99.599998,101.449997,99.599998,100.500000,100.173508,303237,0.009036,NaN
2019-01-14,102.400002,102.400002,99.599998,100.000000,99.675133,202494,-0.004975,NaN
2019-01-15,101.000000,101.000000,99.000000,99.900002,99.575462,274422,-0.001000,NaN
2019-01-16,100.500000,100.699997,98.099998,98.650002,98.329514,204529,-0.012513,NaN
2019-01-17,99.300003,100.800003,97.949997,99.000000,98.678375,264450,0.003548,NaN
2019-01-18,98.500000,100.449997,98.000000,98.300003,97.980652,264363,-0.007071,NaN
2019-01-21,99.000000,99.550003,98.000000,98.949997,98.628540,214830,0.006612,46.024743
2019-01-22,99.349998,99.349998,97.550003,98.150002,97.831146,181990,-0.008085,40.883161
2019-01-23,98.900002,99.400002,97.199997,98.000000,97.681625,191067,-0.001528,39.985769
2019-01-24,99.000000,101.699997,98.050003,100.500000,100.173508,241421,0.025510,56.885190
2019-01-25,100.300003,100.349998,97.400002,97.949997,97.631790,182604,-0.025373,43.498911
2019-01-28,99.150002,102.000000,95.500000,100.699997,100.372856,228223,0.028076,55.577558

In [30]:
## Computing Volatility
import numpy as np
# Compute the logarithmic returns using the Closing price
Swan_Energy['Log_Ret'] = np.log(Swan_Energy['Close'] / Swan_Energy['Close'].shift(1))

# Compute Volatility using the pandas rolling standard deviation function
Swan_Energy['Volatility'] = Swan_Energy['Log_Ret'].rolling(window=14).std() * np.sqrt(14)
Swan_Energy.head(30)

# Plot the NIFTY Price series and the Volatility
# hdfc[['Close', 'Volatility']].plot(kind = "line", subplots=True, color='blue',figsize=(8, 6))

,Open,High,Low,Close,Adj Close,Volume,Swan_Energy_Daily_Returns,RSI,Log_Ret,Volatility
Date,,,,,,,,,,
2019-01-01,101.699997,102.300003,99.500000,100.099998,99.774803,267114,NaN,NaN,NaN,NaN
2019-01-02,100.199997,100.900002,97.000000,97.699997,97.382591,326180,-0.023976,NaN,-0.024268,NaN
2019-01-03,98.250000,99.500000,97.849998,98.800003,98.479034,215418,0.011259,NaN,0.011196,NaN
2019-01-04,98.800003,101.000000,98.000000,99.449997,99.126907,219293,0.006579,NaN,0.006557,NaN
2019-01-07,100.699997,100.699997,98.050003,98.900002,98.578697,324370,-0.005530,NaN,-0.005546,NaN
2019-01-08,99.699997,99.699997,98.099998,98.349998,98.030487,192394,-0.005561,NaN,-0.005577,NaN
2019-01-09,99.000000,99.000000,98.000000,98.300003,97.980652,429586,-0.000508,NaN,-0.000508,NaN
2019-01-10,99.300003,101.800003,97.400002,99.599998,99.276428,227875,0.013225,NaN,0.013138,NaN
2019-01-11,99.599998,101.449997,99.599998,100.500000,100.173508,303237,0.009036,NaN,0.008996,NaN
2019-01-14,102.400002,102.400002,99.599998,100.000000,99.675133,202494,-0.004975,NaN,-0.004988,NaN
2019-01-15,101.000000,101.000000,99.000000,99.900002,99.575462,274422,-0.001000,NaN,-0.001000,NaN
2019-01-16,100.500000,100.699997,98.099998,98.650002,98.329514,204529,-0.012513,NaN,-0.012591,NaN
2019-01-17,99.300003,100.800003,97.949997,99.000000,98.678375,264450,0.003548,NaN,0.003542,NaN
2019-01-18,98.500000,100.449997,98.000000,98.300003,97.980652,264363,-0.007071,NaN,-0.007096,NaN
2019-01-21,99.000000,99.550003,98.000000,98.949997,98.628540,214830,0.006612,46.024743,0.006591,0.038188
2019-01-22,99.349998,99.349998,97.550003,98.150002,97.831146,181990,-0.008085,40.883161,-0.008118,0.030061
2019-01-23,98.900002,99.400002,97.199997,98.000000,97.681625,191067,-0.001528,39.985769,-0.001529,0.027708
2019-01-24,99.000000,101.699997,98.050003,100.500000,100.173508,241421,0.025510,56.885190,0.025190,0.037435
2019-01-25,100.300003,100.349998,97.400002,97.949997,97.631790,182604,-0.025373,43.498911,-0.025701,0.045617
2019-01-28,99.150002,102.000000,95.500000,100.699997,100.372856,228223,0.028076,55.577558,0.027689,0.053267
2019-01-29,100.699997,100.699997,97.500000,97.949997,97.631790,193581,-0.027309,45.220041,-0.027689,0.060866
2019-01-30,98.699997,98.699997,96.550003,97.199997,96.884224,193519,-0.007657,42.884700,-0.007686,0.059477
2019-01-31,97.900002,98.500000,96.250000,97.250000,96.934067,197300,0.000514,43.094628,0.000514,0.058424
2019-02-01,97.849998,98.599998,96.699997,97.800003,97.482285,175360,0.005656,45.457215,0.005640,0.058872
2019-02-04,97.099998,98.599998,95.000000,97.849998,97.532112,222445,0.000511,45.676873,0.000511,0.058907
2019-02-05,97.500000,99.000000,96.150002,98.400002,98.080330,183984,0.005621,48.138670,0.005605,0.058015
2019-02-06,98.550003,99.000000,96.550003,97.250000,96.934067,166058,-0.011687,43.701925,-0.011756,0.058967
2019-02-07,97.650002,98.449997,95.750000,96.449997,96.136665,154210,-0.008226,40.892784,-0.008260,0.059102
2019-02-08,97.500000,98.000000,95.400002,97.900002,97.581955,201671,0.015034,47.452244,0.014922,0.060869
2019-02-11,98.849998,98.900002,95.099998,96.349998,96.036987,219959,-0.015833,42.101091,-0.015959,0.062376

In [31]:
# Calculate the 14-day simple moving average of the closing prices
Swan_Energy["Moving_Average"] = Swan_Energy['Close'].rolling(window=14).mean()

Swan_Energy.head(30)

,Open,High,Low,Close,Adj Close,Volume,Swan_Energy_Daily_Returns,RSI,Log_Ret,Volatility,Moving_Average
Date,,,,,,,,,,,
2019-01-01,101.699997,102.300003,99.500000,100.099998,99.774803,267114,NaN,NaN,NaN,NaN,NaN
2019-01-02,100.199997,100.900002,97.000000,97.699997,97.382591,326180,-0.023976,NaN,-0.024268,NaN,NaN
2019-01-03,98.250000,99.500000,97.849998,98.800003,98.479034,215418,0.011259,NaN,0.011196,NaN,NaN
2019-01-04,98.800003,101.000000,98.000000,99.449997,99.126907,219293,0.006579,NaN,0.006557,NaN,NaN
2019-01-07,100.699997,100.699997,98.050003,98.900002,98.578697,324370,-0.005530,NaN,-0.005546,NaN,NaN
2019-01-08,99.699997,99.699997,98.099998,98.349998,98.030487,192394,-0.005561,NaN,-0.005577,NaN,NaN
2019-01-09,99.000000,99.000000,98.000000,98.300003,97.980652,429586,-0.000508,NaN,-0.000508,NaN,NaN
2019-01-10,99.300003,101.800003,97.400002,99.599998,99.276428,227875,0.013225,NaN,0.013138,NaN,NaN
2019-01-11,99.599998,101.449997,99.599998,100.500000,100.173508,303237,0.009036,NaN,0.008996,NaN,NaN
2019-01-14,102.400002,102.400002,99.599998,100.000000,99.675133,202494,-0.004975,NaN,-0.004988,NaN,NaN
2019-01-15,101.000000,101.000000,99.000000,99.900002,99.575462,274422,-0.001000,NaN,-0.001000,NaN,NaN
2019-01-16,100.500000,100.699997,98.099998,98.650002,98.329514,204529,-0.012513,NaN,-0.012591,NaN,NaN
2019-01-17,99.300003,100.800003,97.949997,99.000000,98.678375,264450,0.003548,NaN,0.003542,NaN,NaN
2019-01-18,98.500000,100.449997,98.000000,98.300003,97.980652,264363,-0.007071,NaN,-0.007096,NaN,99.110715
2019-01-21,99.000000,99.550003,98.000000,98.949997,98.628540,214830,0.006612,46.024743,0.006591,0.038188,99.028572
2019-01-22,99.349998,99.349998,97.550003,98.150002,97.831146,181990,-0.008085,40.883161,-0.008118,0.030061,99.060715
2019-01-23,98.900002,99.400002,97.199997,98.000000,97.681625,191067,-0.001528,39.985769,-0.001529,0.027708,99.003572
2019-01-24,99.000000,101.699997,98.050003,100.500000,100.173508,241421,0.025510,56.885190,0.025190,0.037435,99.078572
2019-01-25,100.300003,100.349998,97.400002,97.949997,97.631790,182604,-0.025373,43.498911,-0.025701,0.045617,99.010714
2019-01-28,99.150002,102.000000,95.500000,100.699997,100.372856,228223,0.028076,55.577558,0.027689,0.053267,99.178571
2019-01-29,100.699997,100.699997,97.500000,97.949997,97.631790,193581,-0.027309,45.220041,-0.027689,0.060866,99.153571
2019-01-30,98.699997,98.699997,96.550003,97.199997,96.884224,193519,-0.007657,42.884700,-0.007686,0.059477,98.982142
2019-01-31,97.900002,98.500000,96.250000,97.250000,96.934067,197300,0.000514,43.094628,0.000514,0.058424,98.749999
2019-02-01,97.849998,98.599998,96.699997,97.800003,97.482285,175360,0.005656,45.457215,0.005640,0.058872,98.592857
2019-02-04,97.099998,98.599998,95.000000,97.849998,97.532112,222445,0.000511,45.676873,0.000511,0.058907,98.446428
2019-02-05,97.500000,99.000000,96.150002,98.400002,98.080330,183984,0.005621,48.138670,0.005605,0.058015,98.428571
2019-02-06,98.550003,99.000000,96.550003,97.250000,96.934067,166058,-0.011687,43.701925,-0.011756,0.058967,98.303571
2019-02-07,97.650002,98.449997,95.750000,96.449997,96.136665,154210,-0.008226,40.892784,-0.008260,0.059102,98.171428
2019-02-08,97.500000,98.000000,95.400002,97.900002,97.581955,201671,0.015034,47.452244,0.014922,0.060869,98.096428
2019-02-11,98.849998,98.900002,95.099998,96.349998,96.036987,219959,-0.015833,42.101091,-0.015959,0.062376,97.967856